### ISSUE TITLE
HTTP 400 when trying any inter ledger transactoin

### ISSUE THREAD

**Issue by melvincarvalho** [interledger/five-bells-demo#25]
I get a 400 error when trying:

```
payment from http://localhost:3007 to http://localhost:3007
jquery.js:8630 PUT http://localhost:5001/payments 400 (Bad Request)
```

log:
```

ledger-ledger7 2016-01-28T13:21:37.549Z koa INFO   --> PUT /transfers/4a835880-7017-4c04-b557-2df5ff29590f 400 11ms -
visualization 2016-01-28T13:21:37.549Z error-handler ERROR Error: Bad Request
visualization     at Request.callback (/var/www/ld/dev/five-bells-demo/node_modules/five-bells-visualization/node_modules/five-bells-sender/node_modules/superagent/lib/node/index.js:826:17)
visualization     at IncomingMessage.<anonymous> (/var/www/ld/dev/five-bells-demo/node_modules/five-bells-visualization/node_modules/five-bells-sender/node_modules/superagent/lib/node/index.js:1049:12)
visualization     at emitNone (events.js:85:20)
visualization     at IncomingMessage.emit (events.js:179:7)
visualization     at endReadableNT (_stream_readable.js:906:12)
visualization     at nextTickCallbackWith2Args (node.js:474:9)
visualization     at process._tickCallback (node.js:388:17)
visualization 2016-01-28T13:21:37.550Z koa INFO   --> PUT /payments 400 250ms -
```

some previous messages:

```
visualization got quotes for 3 paths
visualization got cheapest path: [{"source_transfers":[{"ledger":"http://localhost:3007","credits":[{"amount":"1.05","account":"http://localhost:3007/accounts/millie"}],"expiry_duration":"6"}],"destination_transfers":[{"ledger":"http://localhost:3003","debits":[{"amount":"0.17","account":"http://localhost:3003/accounts/millie"}],"expiry_duration":"5"}],"id":"http://localhost:4004/payments/11cad97d-e746-416a-94b3-fc9aae16a431"},{"source_transfers":[{"ledger":"http://localhost:3003","credits":[{"amount":"0.17","account":"http://localhost:3003/accounts/millie"}],"expiry_duration":"5"}],"destination_transfers":[{"ledger":"http://localhost:3007","debits":[{"amount":"1.00","account":"http://localhost:3007/accounts/millie"}],"expiry_duration":"4"}],"id":"http://localhost:4004/payments/8e00ba17-6365-4a39-8df9-06d0b8a4886b"}]
ledger-ledger7 2016-01-28T13:21:37.538Z koa INFO   <-- PUT /transfers/4a835880-7017-4c04-b557-2df5ff29590f
ledger-ledger7 2016-01-28T13:21:37.546Z error-handler WARN Invalid body: Body did not match schema Transfer
ledger-ledger7 2016-01-28T13:21:37.547Z error-handler DEBUG -- ValidationError: Additional properties not allowed
ledger-ledger7 2016-01-28T13:21:37.547Z error-handler DEBUG    /allOf/0/additionalProperties

```

Any ideas why?  I'll try and look thru the code further

**Comment by emschwartz** [comment]
I think that might be because the `five-bells-sender` doesn't currently support same-ledger payments. There's a ticket for it here: https://github.com/interledger/five-bells-sender/issues/7 and that should be fixed by next week

**Comment by emschwartz** [comment]
It looks like this might be due to properties added to the transfer for Atomic mode that aren't being recognized by the ledger or the schema validator in `five-bells-shared`

**Comment by sentientwaffle** [comment]
@melvincarvalho: The visualization was using a version of five-bells-sender that was incompatible with the connector's five-bells-shared. I have bumped the visualization (2.2.1), so if you re-install five-bells-demo's dependencies it should work.
